# Generated by Django 5.2 on 2025-04-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SquatAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rep", models.PositiveIntegerField()),
                ("duration_sec", models.FloatField()),
                (
                    "back_straight",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=10
                    ),
                ),
                (
                    "knees_over_toes",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=10
                    ),
                ),
                ("min_depth", models.FloatField()),
                ("valid_depth", models.BooleanField()),
            ],
        ),
    ]
